//
// MATLAB Compiler: 4.1 (R14SP1)
// Date: Fri Sep 15 07:49:49 2006
// Arguments: "-B" "macro_default" "-B" "cpplib:matlabtest" "-W"
// "cpplib:matlabtest" "-T" "link:lib" "garchpq_java.m" "darraytest.m"
// "inttest.m" "numtest.m" "sarraytest.m" "stringtest.m" "graphtest.m" 
//


#ifdef __cplusplus
extern "C" {
#endif
extern const unsigned char __MCC_matlabtest_public_data[] = {'3', '0', '8',
                                                             '1', '9', 'D',
                                                             '3', '0', '0',
                                                             'D', '0', '6',
                                                             '0', '9', '2',
                                                             'A', '8', '6',
                                                             '4', '8', '8',
                                                             '6', 'F', '7',
                                                             '0', 'D', '0',
                                                             '1', '0', '1',
                                                             '0', '1', '0',
                                                             '5', '0', '0',
                                                             '0', '3', '8',
                                                             '1', '8', 'B',
                                                             '0', '0', '3',
                                                             '0', '8', '1',
                                                             '8', '7', '0',
                                                             '2', '8', '1',
                                                             '8', '1', '0',
                                                             '0', 'C', '4',
                                                             '9', 'C', 'A',
                                                             'C', '3', '4',
                                                             'E', 'D', '1',
                                                             '3', 'A', '5',
                                                             '2', '0', '6',
                                                             '5', '8', 'F',
                                                             '6', 'F', '8',
                                                             'E', '0', '1',
                                                             '3', '8', 'C',
                                                             '4', '3', '1',
                                                             '5', 'B', '4',
                                                             '3', '1', '5',
                                                             '2', '7', '7',
                                                             'E', 'D', '3',
                                                             'F', '7', 'D',
                                                             'A', 'E', '5',
                                                             '3', '0', '9',
                                                             '9', 'D', 'B',
                                                             '0', '8', 'E',
                                                             'E', '5', '8',
                                                             '9', 'F', '8',
                                                             '0', '4', 'D',
                                                             '4', 'B', '9',
                                                             '8', '1', '3',
                                                             '2', '6', 'A',
                                                             '5', '2', 'C',
                                                             'C', 'E', '4',
                                                             '3', '8', '2',
                                                             'E', '9', 'F',
                                                             '2', 'B', '4',
                                                             'D', '0', '8',
                                                             '5', 'E', 'B',
                                                             '9', '5', '0',
                                                             'C', '7', 'A',
                                                             'B', '1', '2',
                                                             'E', 'D', 'E',
                                                             '2', 'D', '4',
                                                             '1', '2', '9',
                                                             '7', '8', '2',
                                                             '0', 'E', '6',
                                                             '3', '7', '7',
                                                             'A', '5', 'F',
                                                             'E', 'B', '5',
                                                             '6', '8', '9',
                                                             'D', '4', 'E',
                                                             '6', '0', '3',
                                                             '2', 'F', '6',
                                                             '0', 'C', '4',
                                                             '3', '0', '7',
                                                             '4', 'A', '0',
                                                             '4', 'C', '2',
                                                             '6', 'A', 'B',
                                                             '7', '2', 'F',
                                                             '5', '4', 'B',
                                                             '5', '1', 'B',
                                                             'B', '4', '6',
                                                             '0', '5', '7',
                                                             '8', '7', '8',
                                                             '5', 'B', '1',
                                                             '9', '9', '0',
                                                             '1', '4', '3',
                                                             '1', '4', 'A',
                                                             '6', '5', 'F',
                                                             '0', '9', '0',
                                                             'B', '6', '1',
                                                             'F', 'C', '2',
                                                             '0', '1', '6',
                                                             '9', '4', '5',
                                                             '3', 'B', '5',
                                                             '8', 'F', 'C',
                                                             '8', 'B', 'A',
                                                             '4', '3', 'E',
                                                             '6', '7', '7',
                                                             '6', 'E', 'B',
                                                             '7', 'E', 'C',
                                                             'D', '3', '1',
                                                             '7', '8', 'B',
                                                             '5', '6', 'A',
                                                             'B', '0', 'F',
                                                             'A', '0', '6',
                                                             'D', 'D', '6',
                                                             '4', '9', '6',
                                                             '7', 'C', 'B',
                                                             '1', '4', '9',
                                                             'E', '5', '0',
                                                             '2', '0', '1',
                                                             '1', '1', '\0'};

extern const char *__MCC_matlabtest_name_data = "matlabtest";

extern const char *__MCC_matlabtest_root_data = "";

extern const unsigned char __MCC_matlabtest_session_data[] = {'1', '1', '5',
                                                              'F', '7', '2',
                                                              'B', '5', '9',
                                                              'E', '6', 'B',
                                                              '4', 'B', 'C',
                                                              '3', '4', '0',
                                                              '5', 'B', '5',
                                                              'F', 'F', '2',
                                                              '7', 'F', '7',
                                                              'D', '8', 'F',
                                                              '0', '0', '1',
                                                              '7', 'A', '0',
                                                              '5', '4', '6',
                                                              'D', 'A', 'D',
                                                              '8', '2', '8',
                                                              '7', '7', '9',
                                                              '6', 'A', '3',
                                                              '1', '3', '8',
                                                              '8', 'B', '3',
                                                              '2', 'D', '1',
                                                              '1', '9', '1',
                                                              '7', '7', '9',
                                                              '2', '4', '2',
                                                              'A', '5', '0',
                                                              '1', '5', '3',
                                                              '6', 'A', '6',
                                                              '1', 'A', 'A',
                                                              'A', 'C', '5',
                                                              'B', '1', 'D',
                                                              '2', '8', '9',
                                                              '8', '0', 'F',
                                                              '2', 'B', 'C',
                                                              '7', '7', '3',
                                                              'F', 'E', 'C',
                                                              '3', 'C', '7',
                                                              '4', 'F', '8',
                                                              '1', 'E', '0',
                                                              'A', '5', '4',
                                                              '0', 'A', 'A',
                                                              '3', 'B', '5',
                                                              '9', '1', '2',
                                                              'B', '3', '2',
                                                              'D', '5', '3',
                                                              '2', '2', '3',
                                                              'E', 'C', 'F',
                                                              '8', '7', '6',
                                                              'B', 'E', '8',
                                                              '3', '4', 'D',
                                                              '8', '9', '0',
                                                              '7', 'A', '4',
                                                              '1', 'F', 'F',
                                                              'C', 'E', 'B',
                                                              'E', 'C', '0',
                                                              '0', '1', 'D',
                                                              '1', 'C', '5',
                                                              '1', '1', '4',
                                                              'B', '7', 'B',
                                                              '8', '2', '6',
                                                              '7', 'B', 'A',
                                                              '2', '6', 'A',
                                                              '9', '9', 'C',
                                                              '7', '3', '7',
                                                              '1', '5', '4',
                                                              '3', '5', 'C',
                                                              '0', '1', '2',
                                                              '2', '6', 'C',
                                                              '0', '2', 'E',
                                                              '5', '1', '0',
                                                              '3', '5', 'D',
                                                              'B', '5', '7',
                                                              '0', '8', 'C',
                                                              'A', '6', '5',
                                                              '5', '2', '3',
                                                              'B', '5', '9',
                                                              'D', '9', '9',
                                                              'F', 'C', 'B',
                                                              'E', '8', 'F',
                                                              '6', 'D', '9',
                                                              '2', 'D', '1',
                                                              '4', '8', 'F',
                                                              '1', '3', 'F',
                                                              'B', 'C', '9',
                                                              'A', '1', '4',
                                                              '6', '2', '1',
                                                              '7', '0', 'C',
                                                              '2', '\0'};

const char *__MCC_matlabtest_matlabpath_data[] = {"matlabtest/",
                                                  "toolbox/compiler/deploy/",
                                                  "Analysis/jpl_toolbox/diagn/",
                                                  "Analysis/jpl_toolbox/distrib/",
                                                  "Analysis/jpl_toolbox/garch/",
                                                  "Analysis/jpl_toolbox/garch/Garch/",
                                                  "Analysis/jpl_toolbox/regress/",
                                                  "Analysis/jpl_toolbox/util/",
                                                  "$TOOLBOXMATLABDIR/general/",
                                                  "$TOOLBOXMATLABDIR/ops/",
                                                  "$TOOLBOXMATLABDIR/lang/",
                                                  "$TOOLBOXMATLABDIR/elmat/",
                                                  "$TOOLBOXMATLABDIR/elfun/",
                                                  "$TOOLBOXMATLABDIR/specfun/",
                                                  "$TOOLBOXMATLABDIR/matfun/",
                                                  "$TOOLBOXMATLABDIR/datafun/",
                                                  "$TOOLBOXMATLABDIR/polyfun/",
                                                  "$TOOLBOXMATLABDIR/funfun/",
                                                  "$TOOLBOXMATLABDIR/sparfun/",
                                                  "$TOOLBOXMATLABDIR/scribe/",
                                                  "$TOOLBOXMATLABDIR/graph2d/",
                                                  "$TOOLBOXMATLABDIR/graph3d/",
                                                  "$TOOLBOXMATLABDIR/specgraph/",
                                                  "$TOOLBOXMATLABDIR/graphics/",
                                                  "$TOOLBOXMATLABDIR/uitools/",
                                                  "$TOOLBOXMATLABDIR/strfun/",
                                                  "$TOOLBOXMATLABDIR/imagesci/",
                                                  "$TOOLBOXMATLABDIR/iofun/",
                                                  "$TOOLBOXMATLABDIR/audiovideo/",
                                                  "$TOOLBOXMATLABDIR/timefun/",
                                                  "$TOOLBOXMATLABDIR/datatypes/",
                                                  "$TOOLBOXMATLABDIR/verctrl/",
                                                  "$TOOLBOXMATLABDIR/codetools/",
                                                  "$TOOLBOXMATLABDIR/helptools/",
                                                  "$TOOLBOXMATLABDIR/winfun/",
                                                  "$TOOLBOXMATLABDIR/demos/",
                                                  "toolbox/local/",
                                                  "toolbox/optim/",
                                                  "toolbox/shared/optimlib/",
                                                  "toolbox/compiler/",
                                                  "toolbox/database/database/"};
extern const int __MCC_matlabtest_matlabpath_data_count = 41;

const char *__MCC_matlabtest_classpath_data[] = {"java/jar/toolbox/database.jar"};
extern const int __MCC_matlabtest_classpath_data_count = 1;

extern const char *__MCC_matlabtest_mcr_application_options[] = { "" };
extern const int __MCC_matlabtest_mcr_application_option_count = 0;
extern const char *__MCC_matlabtest_mcr_runtime_options[] = { "" };
extern const int __MCC_matlabtest_mcr_runtime_option_count = 0;
#ifdef __cplusplus
}
#endif


